[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "mitemp_scan"
author = "Jon"
author-email = "jonathan.stott@gmail.com"

[tool.flit.scripts]
mitemp_scan = "mitemp_scan:cli"
